server:
  port: 8111
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
debug: true
spring:
  application:
    name: auto-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234qwer
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
